"""Prepare the real-instance end-to-end run.

Reads each instance's self-generated API key out of its config.xml, gives the
instances distinguishing data (root folder, tag, one real title fetched from the
live metadata servers), and renders the proxy config that points at them.

Stdlib only, so it runs on the host with no virtualenv.
"""

from __future__ import annotations

import json
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

HERE = Path(__file__).parent
GENERATED = HERE / "generated"

INSTANCES = [
    # container,             app,      host port, root folder,          tag,          title,          external id
    ("real-sonarr-main", "sonarr", 19101, "/data/tv", "mainshows", "Breaking Bad", 81189),
    ("real-sonarr-anime", "sonarr", 19102, "/data/anime", "animeshows", "Cowboy Bebop", 76885),
    ("real-radarr-main", "radarr", 19103, "/data/movies", "mainfilms", "Dune", 438631),
    ("real-radarr-anime", "radarr", 19104, "/data/anime-movies", "animefilms", "Your Name", 372058),
]

COMBINED_KEYS = {
    "sonarr": "real-sonarr-combined-key-000001",
    "radarr": "real-radarr-combined-key-000001",
}


def api_key(container: str) -> str:
    out = subprocess.run(
        ["docker", "exec", container, "cat", "/config/config.xml"],
        capture_output=True, text=True, check=True,
    ).stdout
    start = out.index("<ApiKey>") + len("<ApiKey>")
    return out[start : out.index("</ApiKey>", start)].strip()


def call(port: int, key: str, path: str, method: str = "GET", body: dict | list | None = None):
    request = urllib.request.Request(
        f"http://127.0.0.1:{port}{path}",
        method=method,
        headers={"X-Api-Key": key, "Content-Type": "application/json"},
        data=json.dumps(body).encode() if body is not None else None,
    )
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            raw = response.read()
            return response.status, (json.loads(raw) if raw else None)
    except urllib.error.HTTPError as exc:
        return exc.code, exc.read().decode("utf-8", "replace")


def wait_ready(port: int, key: str, label: str, attempts: int = 60) -> None:
    for _ in range(attempts):
        status, _ = call(port, key, "/api/v3/system/status")
        if status == 200:
            return
        time.sleep(3)
    raise SystemExit(f"{label} never became ready on port {port}")


def ensure_root_folder(port: int, key: str, path: str) -> None:
    _, existing = call(port, key, "/api/v3/rootfolder")
    if isinstance(existing, list) and any(r.get("path") == path for r in existing):
        return
    call(port, key, "/api/v3/rootfolder", "POST", {"path": path})


def ensure_tag(port: int, key: str, label: str) -> None:
    _, existing = call(port, key, "/api/v3/tag")
    if isinstance(existing, list) and any(t.get("label") == label for t in existing):
        return
    call(port, key, "/api/v3/tag", "POST", {"label": label})


def ensure_title(port: int, key: str, app: str, title: str, external: int,
                 root: str) -> bool:
    """Add one real title, fetched from the live metadata server.

    Returns False when the metadata lookup is unreachable, so an offline run
    degrades to "no library content" instead of failing outright.
    """
    entity = "series" if app == "sonarr" else "movie"
    id_field = "tvdbId" if app == "sonarr" else "tmdbId"

    _, library = call(port, key, f"/api/v3/{entity}")
    if isinstance(library, list) and any(r.get(id_field) == external for r in library):
        return True

    term = "tvdb:" if app == "sonarr" else "tmdb:"
    status, hits = call(port, key, f"/api/v3/{entity}/lookup?term={term}{external}")
    if status != 200 or not isinstance(hits, list) or not hits:
        print(f"  ! lookup for {title} failed ({status}); skipping the add")
        return False

    payload = dict(hits[0])
    payload.update({
        "qualityProfileId": 1,
        "rootFolderPath": root,
        "monitored": False,  # never let a test rig start downloading
        "addOptions": (
            {"monitor": "none", "searchForMissingEpisodes": False}
            if app == "sonarr"
            else {"monitor": "none", "searchForMovie": False}
        ),
    })
    if app == "sonarr":
        payload["seasonFolder"] = True

    status, created = call(port, key, f"/api/v3/{entity}", "POST", payload)
    if status not in (200, 201):
        print(f"  ! adding {title} returned {status}: {str(created)[:200]}")
        return False
    print(f"  + {title} added as id {created.get('id')}")
    return True


def render_config(keys: dict[str, str]) -> Path:
    GENERATED.mkdir(exist_ok=True)
    lines = [
        "# Generated by setup_real.py -- do not edit by hand.",
        "server:",
        "  host: 0.0.0.0",
        "  unified_port: 8787",
        "  log_level: debug",
        "  cache_ttl: 0",
        "  fail_open: true",
        "",
        "apps:",
    ]
    for app in ("sonarr", "radarr"):
        members = [i for i in INSTANCES if i[1] == app]
        lines += [
            f"  {app}:",
            f"    api_key: {COMBINED_KEYS[app]}",
            f"    port: {8989 if app == 'sonarr' else 7878}",
            f"    instance_name: {app.title()} (combined)",
            "    instances:",
        ]
        for index, (container, _, _, root, _, _, _) in enumerate(members):
            name = container.removeprefix("real-")
            port = 8989 if app == "sonarr" else 7878
            lines += [
                f"      - name: {name}",
                f"        url: http://{container}:{port}",
                f"        api_key: {keys[container]}",
            ]
            if index == 0:
                lines.append("        default: true")
            else:
                lines += [
                    "        routing:",
                    "          series_types: [anime]" if app == "sonarr" else "          genres: [Animation]",
                    f"          root_folders: [\"{root}\"]",
                ]
        lines.append("")

    target = GENERATED / "config.real.yaml"
    target.write_text("\n".join(lines), encoding="utf-8")
    return target


def main() -> int:
    keys: dict[str, str] = {}
    facts: dict[str, dict] = {}

    for container, app, port, root, tag, title, external in INSTANCES:
        print(f"[{container}]")
        key = api_key(container)
        keys[container] = key
        wait_ready(port, key, container)
        ensure_root_folder(port, key, root)
        ensure_tag(port, key, tag)
        added = ensure_title(port, key, app, title, external, root)

        entity = "series" if app == "sonarr" else "movie"
        _, library = call(port, key, f"/api/v3/{entity}")
        _, tags = call(port, key, "/api/v3/tag")
        _, roots = call(port, key, "/api/v3/rootfolder")
        _, profiles = call(port, key, "/api/v3/qualityprofile")
        facts[container.removeprefix("real-")] = {
            "app": app,
            "api_key": key,
            "port": port,
            "root_folder": root,
            "tag": tag,
            "title": title,
            "external_id": external,
            "added": added,
            "library_ids": [r["id"] for r in library] if isinstance(library, list) else [],
            "tag_ids": [t["id"] for t in tags] if isinstance(tags, list) else [],
            "root_ids": [r["id"] for r in roots] if isinstance(roots, list) else [],
            "profile_ids": [p["id"] for p in profiles] if isinstance(profiles, list) else [],
        }
        print(f"  library ids {facts[container.removeprefix('real-')]['library_ids']}, "
              f"tag ids {facts[container.removeprefix('real-')]['tag_ids']}, "
              f"profile ids {facts[container.removeprefix('real-')]['profile_ids']}")

    GENERATED.mkdir(exist_ok=True)
    (GENERATED / "facts.json").write_text(json.dumps(facts, indent=2), encoding="utf-8")
    config = render_config(keys)
    print(f"\nwrote {config}")
    print(f"wrote {GENERATED / 'facts.json'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
